
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oikjfgofirylfmdvnzku.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9pa2pmZ29maXJ5bGZtZHZuemt1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0NTMzNTcsImV4cCI6MjA2MzAyOTM1N30.gYvE-fBgyQYorasos33BmYg-9QvsZDJXUsJN_KFjx6c";

/**
 * Supabase client for the Calculadora Leilões app
 * 
 * This client provides access to the following resources:
 * - Authentication (sign up, sign in, sign out)
 * - User profiles management
 * - Mentorship waitlist registrations
 * - WhatsApp group management
 * 
 * Import the supabase client like this:
 * import { supabase } from "@/integrations/supabase/client";
 */
export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);

/**
 * Helper functions for common Supabase operations
 */

/**
 * Add a user to the mentorship waitlist
 */
export const addToMentorshipWaitlist = async (email: string, phone?: string) => {
  const { data: existingEntry } = await supabase
    .from('mentorship_waitlist')
    .select('*')
    .eq('email', email)
    .single();

  // If user already registered, don't add again
  if (existingEntry) {
    return { success: true, message: 'Você já está na lista de espera.' };
  }

  // Get the current user ID
  const { data: { user } } = await supabase.auth.getUser();
  const userId = user?.id;

  // Now insert the data with the resolved userId
  const { error } = await supabase
    .from('mentorship_waitlist')
    .insert({
      email,
      phone,
      user_id: userId || null
    });

  if (error) {
    console.error('Error adding to waitlist:', error);
    return { success: false, message: 'Erro ao adicionar à lista de espera.' };
  }

  return { success: true, message: 'Adicionado à lista de espera com sucesso!' };
};

/**
 * Update user's WhatsApp group joined status
 */
export const updateWhatsAppGroupStatus = async (joined: boolean) => {
  const { data: { user } } = await supabase.auth.getUser();
  
  if (!user) {
    return { success: false, message: 'Usuário não autenticado.' };
  }

  const { error } = await supabase
    .from('profiles')
    .update({ whatsapp_group_joined: joined })
    .eq('id', user.id);

  if (error) {
    console.error('Error updating WhatsApp status:', error);
    return { success: false, message: 'Erro ao atualizar status do grupo WhatsApp.' };
  }

  return { success: true, message: 'Status do grupo WhatsApp atualizado com sucesso!' };
};

/**
 * Sign in with Google
 */
export const signInWithGoogle = async () => {
  return await supabase.auth.signInWithOAuth({
    provider: 'google',
    options: {
      redirectTo: window.location.origin
    }
  });
};

/**
 * Check if user has free trial access
 * User has free trial if they have joined the WhatsApp group
 */
export const checkUserAccess = async () => {
  const { data: { user } } = await supabase.auth.getUser();
  
  if (!user) {
    return { hasAccess: false, reason: 'not_authenticated' };
  }

  // Check if user has joined WhatsApp group
  const { data } = await supabase
    .from('profiles')
    .select('whatsapp_group_joined')
    .eq('id', user.id)
    .single();

  if (!data) {
    return { hasAccess: false, reason: 'no_profile' };
  }

  if (data.whatsapp_group_joined) {
    return { hasAccess: true, reason: 'whatsapp_trial' };
  }

  // Future: add check for paid subscription
  // if (data.subscription_status === 'active') {
  //   return { hasAccess: true, reason: 'paid_subscription' };
  // }

  return { hasAccess: false, reason: 'no_access' };
};
